# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b2e81f917c1a530443fe4cff9e349a7018fdc928d14d727fbaa352c735da4a8f7d24ef516f0517e2e0aa3606fb687304c392d639c552053bcdf4ffd37cc7714
  aliyun_oss:
    #endpoint: oss-cn-hangzhou-internal.aliyuncs.com
    endpoint: oss-cn-hangzhou.aliyuncs.com  
    access_key_id: LTAIp1ffbh0rL2XE
    access_key_secret: r1krFzBLNzKLxIwQqnwe6S3EUcCUox

test:
  secret_key_base: 8f6817b649253a76a89e48ee87c9c018cb53618213a273b54b6243befa82453d53bcfcb34e0ac883adfd091fdbf31e4c7b9e4edb0cae6caccdd17e4e2d15b14c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
    endpoint: oss-cn-hangzhou-internal.aliyuncs.com
    #endpoint: oss-cn-hangzhou.aliyuncs.com  
    access_key_id: LTAIp1ffbh0rL2XE
    access_key_secret: r1krFzBLNzKLxIwQqnwe6S3EUcCUox
